pipeline{
environment{
version = "Version_$BUILD_NUMBER"
}
agent {
  label 'docker'
}
stages {
  stage('Checkout') {
    steps {
     git 'https://github.com/JevitaD/helm.git'
    }
  }
/*
  stage('Build') {
    steps {
       sh 'mvn -f MyAwesomeApp/pom.xml clean install'  
    }
  }
 stage('Build Image') {
  steps {
    script{
      dockerImage = docker.build("jevi17/myreponode:$version","MyAwesomeApp")
    }
  }
}
stage('Push Image') {
	steps {
		script { 
			docker.withRegistry('','dockerhub') {
				dockerImage.push() 
			}
		}
	}
 }
*/	
 stage('DEPLOY IMAGE') {
  steps {
    script { 
	docker.withRegistry( '','dockerhub' ) { 
	  dockerImage.run('-it -p 8080:8085 --name "container-$version"') 
	 }
    } 
  }
}

}
}
