pipeline{
environment{
version = "Version_$BUILD_NUMBER"
}
agent {
  label 'docker'
}
stages {
  stage('Checkout') {
    steps {
     checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/JevitaD/CICD.git']]])
    }
  }

  stage('Build') {
    steps {
       sh 'mvn -f MyAwesomeApp/pom.xml clean install'  
    }
  }
 stage('Build Image') {
  steps {
    dockerImage = docker.build("jevi17/myreponode:$version","MyAwesomeApp")
  }
}
}
}
