pipeline{
agent {
  label 'docker'
}
stages {
  stage('Checkout') {
    steps {
     checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/JevitaD/CICD.git']]])
    }
  }

  stage('Build') {
    steps {
       sh 'mvn -f MyAwesomeApp/pom.xml clean install'  
    }
  }

}
}
